sudo: required

services:
  - docker

before_install:
  - docker build -t diadem27/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true diadem27/react-test npm test

after_success:
  - docker build -t diadem27/multi-client ./client
  - docker build -t diadem27/multi-nginx ./nginx
  - docker build -t diadem27/multi-server ./server
  - docker build -t diadem27/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push diadem27/multi-client
  - docker push diadem27/multi-nginx
  - docker push diadem27/multi-server
  - docker push diadem27/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-north-1
  app: multi-docker
  env: multi-docker-env
  bucket_name: elasticbeanstalk-eu-north-1-985086268407
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY