sudo: required

services:
  - docker

before_install:
  - docker build -t diadem27/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true diadem27/react-test npm test

after_success:
  - docker build -t diadem27/multi-client ./client
  - docker build -t diadem27/multi-nginx ./nginx
  - docker build -t diadem27/multi-server ./server
  - docker build -t diadem27/multi-worker ./worker